---
- hosts: all
  become: yes

  tasks:

    # Update all packages with yum
    - name: "Upgrade all packages using yum"
      yum:
        name: '*'
        state: 'latest'

    - name: install java-1.8.0-openjdk-devel
      yum:
        name: "java-1.8.0-openjdk-devel"
        state: 'latest'

    - name: Just force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: installing docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: 'Starting Docker services'
      service:
        name: docker
        state: started

    - name: install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    # Next Play : install jenkins Role
- hosts: all
  become: yes

  roles:
    - { role: geerlingguy.jenkins, when: ansible_system == 'Linux' }



